add test cases for internal/data/db/scan.go
defenseunicorns/uds-security-hub-v1-archive pull request #297
Opened 2024-09-26 18:19 UTC by benjaminwilcox

add test cases for internal/data/db/scan.go

2024-09-26 21:53 UTC, partkyle requested changes

2024-09-26 21:53 UTC, partkyle commented on internal/data/db/scan_test.go
> +		{
These tests are strange because the code that's there is strange. It's not a reasonable expectation that `ctx` or `db` should be `nil` during normal operation. That's covered by using the `NewGormScanManager` method. That's the major reason to use constructors like that.

I think we need to remove all the nil checks instead. They are erroneous. If we checked nil on everything that could be nil, every time it could be nil, the entire codebase would be nil checks.

We need sufficient tests, and if there are `nil` panics they should get picked up by those tests. If not, we'll fix them. But these extra nil checks should be removed.

2024-10-07 15:01 UTC, benjaminwilcox commented on internal/data/db/scan_test.go
> +		{
@partkyle the nil checks have been removed, are there any other changes?

2024-10-07 20:35 UTC, dekkagaijin approved these changes

2024-10-25 19:30 UTC, closed without merging