refactor pkg/semver/semver_test.go
defenseunicorns/uds-security-hub-v1-archive pull request #320
Opened 2024-10-04 17:54 UTC by benjaminwilcox

2024-10-07 23:28 UTC, dekkagaijin requested changes

2024-10-07 23:28 UTC, dekkagaijin commented on pkg/semver/semver_test.go
> +		assert.Equal(t, expected[i], v, "version mismatch at index %d", i)
Does this package automatically print `expected` and `got`? If not we should keep these error messages the same as before (i.e. helpful and idiomatic in Go)

2024-10-07 23:36 UTC, benjaminwilcox commented on pkg/semver/semver_test.go
> +		assert.Equal(t, expected[i], v, "version mismatch at index %d", i)
Yes it does!

2024-10-07 23:40 UTC, benjaminwilcox commented on pkg/semver/semver_test.go
> +		assert.Equal(t, expected[i], v, "version mismatch at index %d", i)
Where errorf would say something like: `Expected version 1.2.3, got 4.5.6`, assert.equal would say something like:
```
Error:      	Not equal: 
            	expected: "1.2.3"
            	actual  : "4.5.6"
Messages:   	version mismatch at index 0
```

2024-10-08 00:15 UTC, dekkagaijin approved these changes

2024-10-25 19:29 UTC, closed without merging